version: 3.1

services:
  nginx:
    container_name: nginx_contacts
    image: nginx:stable
    ports:
      - ${DOCKER_HTTP_PORT}:80
    volumes:
    - .:/app
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php_contacts
    build: ./docker/php
    working_dir: /app
    volumes:
    - .:/app
    - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    - $HOME/.composer/cache:/root/.composer/cache

  php_unit:
    container_name: php_contacts
    build: ./docker/php
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - $HOME/.composer/cache:/root/.composer/cache


  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYQSL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - {DATABASE_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql

